[webserver]
listen = ":8090"
access_log = true
webroot = "../media-ui/dist"

# if ACME / Let's Encrypt used, uncomment listen
[webserver.acme]
enable = false
domains = ["example1.com", "example2.com"]
cache = "/var/www/.cache"

[database]
connection = "user=root dbname=media_server host=localhost port=26257 sslmode=disable"
debug = true
testdata = true
log_level = 0
